version: '3'
services:
  spring:
    container_name: back_dev
    image: localhost:8443/back_dev
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@172.27.10.97:1521:xe"
      SPRING_DATASOURCE_USERNAME: "POP"
      SPRING_DATASOURCE_PASSWORD: "POP"
    volumes:
      - /nfs_shared/spring/upload:/opt/upload
    restart: always